name: Build and Deploy

on:
    push:
        branches:
            - main

concurrency:
    group: ${{ github.repository }}
    cancel-in-progress: true

jobs:
    build-linux:
        runs-on: ubuntu-latest

        env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
            DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v5
                with:
                    submodules: recursive
                    fetch-depth: 1

            -   name: Install toolchains
                run: |
                    ####################################################################################################

                    sudo dpkg --add-architecture i386

                    ####################################################################################################

                    sudo apt-get update
                    sudo apt-get install -y curl rsync openssh-client
                    sudo apt-get install -y wine32 wine64

                    ####################################################################################################

                    WINE_DIR="$(dirname "$(command -v wine)")"

                    if [ ! -e "$WINE_DIR/wine64" ]
                    then
                        sudo ln -s "$WINE_DIR/wine" "$WINE_DIR/wine64"
                    fi

                    ####################################################################################################

                    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.2/install.sh | bash
                    source "${HOME}/.nvm/nvm.sh"
                    nvm install --lts

                    ####################################################################################################

            -   name: Setup SSH
                shell: bash

                run: |
                    ####################################################################################################

                    mkdir -p ~/.ssh/
                    chmod 700 ~/.ssh/

                    echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
                    chmod 600 ~/.ssh/id_rsa

                    eval "$(ssh-agent -s)"
                    ssh-add ~/.ssh/id_rsa

                    ssh-keyscan -H "${DEPLOY_HOST}" >> ~/.ssh/known_hosts
                    chmod 644 ~/.ssh/known_hosts

                    ####################################################################################################

            -   name: Setup project
                shell: bash
                run: |
                    ####################################################################################################

                    source "${HOME}/.nvm/nvm.sh"

                    npm --version
                    node --version
                    wine --version
                    wine64 --version

                    ####################################################################################################

                    npm install
                    npm audit fix

                    ####################################################################################################

            -   name: Build and deploy Nyx Lab Desktop for Linux
                shell: bash
                run: |
                    ####################################################################################################

                    npm run electron-linux

                    scp ./src-electron/target/nyx-lab-*.AppImage "${DEPLOY_USER}@${DEPLOY_HOST}:/var/www/nyxlib.org/download/linux/x86_64/nyx-lab.AppImage"

                    ####################################################################################################

            -   name: Build and deploy Nyx Lab Desktop for Windows
                shell: bash
                run: |
                    ####################################################################################################

                    npm run electron-windows

                    scp ./src-electron/target/nyx-lab-*.exe "${DEPLOY_USER}@${DEPLOY_HOST}:/var/www/nyxlib.org/download/windows/x86_64/nyx-lab.exe"

                    ####################################################################################################

            -   name: Deploy Nyx Lab Web
                shell: bash
                run: |
                    ####################################################################################################

                    rsync -avz --delete ./dist/ "${DEPLOY_USER}@${DEPLOY_HOST}:/var/www/nyxlib.org/lab/"

                    ####################################################################################################

    build-macos:
        runs-on: macos-latest

        env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
            DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v5
                with:
                    submodules: recursive
                    fetch-depth: 1

            -   name: Install toolchains
                run: |
                    ####################################################################################################

                    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.2/install.sh | bash
                    source "${HOME}/.nvm/nvm.sh"
                    nvm install --lts

                    ####################################################################################################

            -   name: Setup SSH
                shell: bash

                run: |
                    ####################################################################################################

                    mkdir -p ~/.ssh/
                    chmod 700 ~/.ssh/

                    echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
                    chmod 600 ~/.ssh/id_rsa

                    eval "$(ssh-agent -s)"
                    ssh-add ~/.ssh/id_rsa

                    ssh-keyscan -H "${DEPLOY_HOST}" >> ~/.ssh/known_hosts
                    chmod 644 ~/.ssh/known_hosts

                    ####################################################################################################

            -   name: Setup project
                shell: bash
                run: |
                    ####################################################################################################

                    source "${HOME}/.nvm/nvm.sh"

                    npm --version
                    node --version

                    ####################################################################################################

                    npm install
                    npm audit fix

                    ####################################################################################################

            -   name: Build and deploy Nyx Lab Desktop for macOS
                shell: bash
                run: |
                    ####################################################################################################

                    npm run electron-macos

                    scp ./src-electron/target/nyx-lab-*.dmg "${DEPLOY_USER}@${DEPLOY_HOST}:/var/www/nyxlib.org/download/macos/universal/nyx-lab.dmg"

                    ####################################################################################################
