name: Build and Deploy

on:
    push:
        branches:
            - main

concurrency:
    group: ${{ github.repository }}
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v5
                with:
                    submodules: recursive
                    fetch-depth: 1

            -   name: Install system dependencies
                run: |
                    sudo dpkg --add-architecture i386

                    sudo apt-get update
                    sudo apt-get install -y curl rsync openssh-client
                    sudo apt-get install -y wine64 wine32 mono-complete

                    WINE_DIR="$(dirname "$(command -v wine)")"

                    if [ ! -e "$WINE_DIR/wine64" ]
                    then
                        sudo ln -s "$WINE_DIR/wine" "$WINE_DIR/wine64"
                    fi

            -   name: Install Node toolchain
                shell: bash
                run: |
                    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.2/install.sh | bash
                    source "${HOME}/.nvm/nvm.sh"
                    nvm install --lts

            -   name: Build project
                shell: bash
                run: |
                    source "${HOME}/.nvm/nvm.sh"

                    npm --version
                    node --version
                    mono --version
                    wine --version
                    wine64 --version

                    npm install && npm run app-prod

                    cd src-electron && npm install && npm run electron-make-linux && npm run electron-make-linux

                    cd src-electron && npm install && npm run electron-make-linux && npm run electron-make-windows

            -   name: Deploy project
                shell: bash
                env:
                    SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                    DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
                    DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
                run: |
                    mkdir -p ~/.ssh/
                    chmod 700 ~/.ssh/

                    echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
                    chmod 600 ~/.ssh/id_rsa

                    eval "$(ssh-agent -s)"
                    ssh-add ~/.ssh/id_rsa

                    ssh-keyscan -H "${DEPLOY_HOST}" >> ~/.ssh/known_hosts
                    chmod 644 ~/.ssh/known_hosts

                    rsync -avz --delete ./dist/ "${DEPLOY_USER}@${DEPLOY_HOST}:/var/www/nyxlib.org/lab/"

                    scp "./src-electron/target/make/AppImage/x64/nyx-lab-*.AppImage" "${DEPLOY_USER}@${DEPLOY_HOST}:/var/www/nyxlib.org/download/linux/x86_64/nyx-lab.AppImage"

                    scp "./src-electron/target/make/squirrel.windows/x64/nyx-lab-*.exe" "${DEPLOY_USER}@${DEPLOY_HOST}:/var/www/nyxlib.org/download/windows/x86_64/nyx-lab-setup.exe"
